'use client'

import './globals.css'

import { Josefin_Sans } from 'next/font/google'
import AuthProvider from '../../Provider/AuthProvider'

// import { Toaster } from 'react-hot-toast'
import { usePathname } from 'next/navigation'

const josefinSans = Josefin_Sans({
  variable: '--font-primary',
  subsets: ['latin'],
  display: 'swap',
})

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  const pathname = usePathname()
  // const isAdminRoute = pathname.startsWith('/admin') // 👈 detect admin

  return (
    <html lang="en">
      <body className={`${josefinSans.variable} antialiased bg-purple-50`}>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  )
}
